# Generated by Django 4.1.7 on 2023-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является клиентом.', verbose_name='Клиент'),
        ),
    ]
