# Generated by Django 4.1.7 on 2023-11-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_worker',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь                                                                                             является сотрудником.', verbose_name='Сотрудником'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь                                                                                         является клиентом.', verbose_name='Клиент'),
        ),
    ]
