# Generated by Django 4.1.7 on 2023-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_worker_alter_customuser_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_worker',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь                                                                                             является сотрудником.', verbose_name='Сотрудник'),
        ),
    ]
