# Generated by Django 4.1.7 on 2023-11-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complectations', '0052_servicesmeta_process_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('В ходе выполнения', '0'), ('Выполнил', '1')], default='0', max_length=50, verbose_name='Статус задачи')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания задачи')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('explanations', models.CharField(max_length=255, verbose_name='Пояснения')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complectations.complectation', verbose_name='Объект')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Доступ пользователей к комплектации')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
