# Generated by Django 4.1.7 on 2023-11-23 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='explanations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пояснения'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('В ходе выполнения', 'В ходе выполнения'), ('Выполнил', 'Выполнил')], default='0', max_length=50, verbose_name='Статус задачи'),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Выполняют задачу'),
        ),
    ]
