# Generated by Django 4.1.7 on 2023-02-28 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Комплектации')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес заказчика')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон заказчика')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='Ссылка на комплектацию')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания коплектации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комплектации')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя товара')),
                ('discription', models.TextField(verbose_name='Описание товара')),
                ('count', models.IntegerField(verbose_name='Количество товаров')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания товара')),
                ('date_order', models.DateField(verbose_name='Дата заказа товара')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Картинка товара')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
