# Generated by Django 4.1.7 on 2023-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='complectation',
        ),
        migrations.AddField(
            model_name='product',
            name='complectation',
            field=models.ManyToManyField(to='complectations.complectation', verbose_name='Выберите комплектацию'),
        ),
    ]
