# Generated by Django 4.1.7 on 2023-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0005_remove_complectation_product_product_complectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcound',
            name='cound',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
