# Generated by Django 4.1.7 on 2023-05-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0007_remove_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество товаров'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='complectation',
        ),
        migrations.DeleteModel(
            name='ProductCound',
        ),
        migrations.AddField(
            model_name='product',
            name='complectation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию'),
            preserve_default=False,
        ),
    ]
