# Generated by Django 4.1.7 on 2023-05-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0008_product_count_remove_product_complectation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sum_price_count',
            field=models.IntegerField(default=1, verbose_name='Цена за все'),
            preserve_default=False,
        ),
    ]
