# Generated by Django 4.1.7 on 2023-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0009_product_sum_price_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meas',
            field=models.CharField(choices=[('1', 'шт'), ('2', 'к/м'), ('3', 'п/м'), ('4', 'литр'), ('5', 'кг')], default='1', max_length=1, verbose_name='Вид ичесления'),
        ),
    ]
