# Generated by Django 4.1.7 on 2023-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0012_product_date_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='В пути', max_length=150, verbose_name='Статус товара'),
        ),
    ]
