# Generated by Django 4.1.7 on 2023-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0014_alter_product_meas'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prepayment',
            field=models.IntegerField(default=0, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='product',
            name='remains',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
            preserve_default=False,
        ),
    ]
