# Generated by Django 4.1.7 on 2023-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0015_product_prepayment_product_remains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Не заказанно', max_length=150, verbose_name='Статус товара'),
        ),
    ]
