# Generated by Django 4.1.7 on 2023-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0016_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Не заказано', 'Не заказано'), ('В пути', 'В пути'), ('На складе', 'На складе')], default='Не заказано', max_length=150, verbose_name='Статус товара'),
        ),
    ]
