# Generated by Django 4.1.7 on 2023-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0017_alter_product_count_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sklad',
            field=models.CharField(default=' ', max_length=150, verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Не заказано', 'Не заказано'), ('В пути', 'В пути'), ('На складе', 'На складе')], default='Не заказано', max_length=50, verbose_name='Статус товара'),
        ),
    ]
