# Generated by Django 4.1.7 on 2023-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0019_alter_product_sklad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_order',
            field=models.DateField(blank=True, verbose_name='Дата заказа товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_shipment',
            field=models.DateField(blank=True, verbose_name='Дата поставки товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sklad',
            field=models.CharField(blank=True, default=' ', max_length=150, verbose_name='Склад'),
        ),
    ]
