# Generated by Django 4.1.7 on 2023-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0022_alter_product_date_order_alter_product_date_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_order',
            field=models.DateField(blank=True, default='00.00.0000', verbose_name='Дата заказа товара'),
        ),
    ]
