# Generated by Django 4.1.7 on 2023-06-01 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complectations', '0025_alter_product_date_order_alter_product_date_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complectation',
            name='author',
        ),
        migrations.AddField(
            model_name='complectation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Доступ пользователей к комплектации'),
        ),
    ]
