# Generated by Django 4.1.7 on 2023-07-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0027_alter_complectation_slug_productsmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmeta',
            name='procent',
            field=models.IntegerField(default=0, verbose_name='Процент наценки'),
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество товара или услуг'),
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='discription',
            field=models.TextField(verbose_name='Описание товара или услуги'),
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='meas',
            field=models.CharField(choices=[('шт', 'штуки'), ('к/м', 'квадратные метры'), ('п/м', 'погоные метры'), ('литр', 'литры'), ('куб', 'кубы'), ('кг', 'килограмы'), ('услуга', 'услуга')], default='1', max_length=8, verbose_name='Вид ичесления'),
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя товара или услуги'),
        ),
    ]
