# Generated by Django 4.1.7 on 2023-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0028_productsmeta_procent_alter_productsmeta_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmeta',
            name='sum_price_procent',
            field=models.IntegerField(default=0, verbose_name='Цена за все с наценкой'),
            preserve_default=False,
        ),
    ]
