# Generated by Django 4.1.7 on 2023-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0029_productsmeta_sum_price_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmeta',
            name='sum_price_procent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена за все с наценкой'),
        ),
    ]
