# Generated by Django 4.1.7 on 2023-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0030_alter_productsmeta_sum_price_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmeta',
            name='sum_price_procent',
            field=models.IntegerField(verbose_name='Цена за все с наценкой'),
        ),
    ]
