# Generated by Django 4.1.7 on 2023-07-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0031_alter_productsmeta_sum_price_procent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик сметы',
                'verbose_name_plural': 'Поставщики сметы',
            },
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='procent',
            field=models.IntegerField(default=0, verbose_name='Процент наценки %'),
        ),
    ]
