# Generated by Django 4.1.7 on 2023-07-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0032_provider_alter_productsmeta_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmeta',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='complectations.provider', verbose_name='Выберите поставщика'),
            preserve_default=False,
        ),
    ]
