# Generated by Django 4.1.7 on 2023-07-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0033_productsmeta_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmeta',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='complectations.provider', verbose_name='Выберите поставщика'),
        ),
    ]
