# Generated by Django 4.1.7 on 2023-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0035_alter_productsmeta_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Группа коплектации',
                'verbose_name_plural': 'Группы коплектаций',
            },
        ),
    ]
