# Generated by Django 4.1.7 on 2023-07-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0036_groupproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complectations.groupproduct', verbose_name='Группа продукта'),
        ),
    ]
