# Generated by Django 4.1.7 on 2023-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0039_productsmeta_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmeta',
            name='date_create',
            field=models.DateField(verbose_name='Дата добавления чека'),
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='payment_status',
            field=models.CharField(choices=[('Оплатил', 'Оплатил'), ('Не оплатил', 'Не оплатил')], max_length=15, verbose_name='Статус оплаты'),
        ),
    ]
