# Generated by Django 4.1.7 on 2023-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0040_alter_productsmeta_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
    ]
