# Generated by Django 4.1.7 on 2023-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0042_productsmeta_expenses_alter_productsmeta_discription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название поступления')),
                ('date_create', models.DateField(verbose_name='Дата поступления')),
                ('price', models.IntegerField(default=0, verbose_name='Сумма поступления')),
                ('summ', models.IntegerField(default=0, verbose_name='Общая сумма поступлений')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productsmeta',
            options={'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='meas',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='prepayment',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='procent',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='remains',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='sum_price_count',
        ),
        migrations.RemoveField(
            model_name='productsmeta',
            name='sum_price_procent',
        ),
        migrations.AlterField(
            model_name='productsmeta',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена чека'),
        ),
        migrations.CreateModel(
            name='ServiceSmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя услуги')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('payment_status', models.CharField(choices=[('Оплатил', 'Оплатил'), ('Не оплатил', 'Не оплатил')], max_length=15, verbose_name='Статус оплаты')),
                ('date_create', models.DateField(verbose_name='Дата добавления')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('meas', models.CharField(choices=[('шт', 'штуки'), ('к/м', 'квадратные метры'), ('п/м', 'погоные метры'), ('литр', 'литры'), ('куб', 'кубы'), ('кг', 'килограмы')], default='1', max_length=8, verbose_name='Вид ичесления')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('price_all', models.IntegerField(default=0, verbose_name='Цена за все')),
                ('procent', models.IntegerField(default=0, verbose_name='Процент %')),
                ('price_procent', models.IntegerField(default=0, verbose_name='Сумма наценки')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
