# Generated by Django 4.1.7 on 2023-07-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0043_receipts_alter_productsmeta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AddField(
            model_name='receipts',
            name='complectation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complectations.complectation', verbose_name='Выберите комплектацию'),
            preserve_default=False,
        ),
    ]
