# Generated by Django 4.1.7 on 2023-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0044_alter_receipts_options_receipts_complectation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='summ',
        ),
        migrations.AddField(
            model_name='receipts',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара или услуги'),
        ),
    ]
