# Generated by Django 4.1.7 on 2023-07-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complectations', '0045_remove_receipts_summ_receipts_discription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'verbose_name': 'Поступление средств', 'verbose_name_plural': 'Пуступления средств'},
        ),
        migrations.AddField(
            model_name='receipts',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил поступление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipts',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание поступления'),
        ),
    ]
