# Generated by Django 4.1.7 on 2023-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0048_complectation_balance_complectation_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма поступления'),
        ),
    ]
