# Generated by Django 4.1.7 on 2023-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0049_alter_receipts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmeta',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена чека'),
        ),
        migrations.AlterField(
            model_name='servicesmeta',
            name='count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='servicesmeta',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicesmeta',
            name='price_all',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за все'),
        ),
        migrations.AlterField(
            model_name='servicesmeta',
            name='price_procent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма наценки'),
        ),
    ]
