# Generated by Django 4.1.7 on 2023-07-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0050_alter_productsmeta_price_alter_servicesmeta_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remains',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sum_price_count',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за все'),
        ),
    ]
