# Generated by Django 4.1.7 on 2023-09-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complectations', '0051_alter_product_count_alter_product_prepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmeta',
            name='process_org',
            field=models.BooleanField(default=False, verbose_name='Организация процесса'),
        ),
    ]
