# Generated by Django 4.1.7 on 2023-11-23 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complectations', '0052_servicesmeta_process_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='complectation',
            name='prorab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prorab', to=settings.AUTH_USER_MODEL, verbose_name='Прораб'),
        ),
        migrations.AlterField(
            model_name='complectation',
            name='slug',
            field=models.SlugField(help_text='**Можно использовать только латинские буквы', max_length=20, unique=True, verbose_name='Ссылка на комплектацию'),
        ),
    ]
